#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable


layout(std430, binding = 0) buffer counterBuffer 
{
   uint numbers[ ];
};


layout(binding = 1, rgba8) uniform image2D storageTexture;

layout (local_size_x = 256) in;


void main() 
{
    // Current SSBO index
    uint index = gl_GlobalInvocationID.x;
    
    if (index >= 10) 
		return;	

	numbers[index] = index;
         atomicAdd(numbers[0],10);

    imageStore(storageTexture, ivec2(0,0), vec4(1));
//numbers[0] += 10;
}

